// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBLlTu5xvvx7mYF9GT2Zn_iQtXAC_Jf3qs',
    appId: '1:508656524886:web:747010f55d2454c6b425f7',
    messagingSenderId: '508656524886',
    projectId: 'grocery-backend-8a5a1',
    authDomain: 'grocery-backend-8a5a1.firebaseapp.com',
    storageBucket: 'grocery-backend-8a5a1.firebasestorage.app',
    measurementId: 'G-23PJM9L7H6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDo-e1NOGGmaVDXj2ZEFRIZzqAjyLGnx94',
    appId: '1:508656524886:android:8f985abda44e5054b425f7',
    messagingSenderId: '508656524886',
    projectId: 'grocery-backend-8a5a1',
    storageBucket: 'grocery-backend-8a5a1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAYOou1iexqu7ExHZ2FzI1DT4zOfnrjiOE',
    appId: '1:508656524886:ios:32259e70870e35d8b425f7',
    messagingSenderId: '508656524886',
    projectId: 'grocery-backend-8a5a1',
    storageBucket: 'grocery-backend-8a5a1.firebasestorage.app',
    iosBundleId: 'com.vishva.groceryapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAYOou1iexqu7ExHZ2FzI1DT4zOfnrjiOE',
    appId: '1:508656524886:ios:77dfab09f3d35b2ab425f7',
    messagingSenderId: '508656524886',
    projectId: 'grocery-backend-8a5a1',
    storageBucket: 'grocery-backend-8a5a1.firebasestorage.app',
    iosBundleId: 'com.example.groceryApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBLlTu5xvvx7mYF9GT2Zn_iQtXAC_Jf3qs',
    appId: '1:508656524886:web:6dc11752e41900a9b425f7',
    messagingSenderId: '508656524886',
    projectId: 'grocery-backend-8a5a1',
    authDomain: 'grocery-backend-8a5a1.firebaseapp.com',
    storageBucket: 'grocery-backend-8a5a1.firebasestorage.app',
    measurementId: 'G-3ZFYEYYT0L',
  );

}